--- MyTermOpts
--- - id integer @readonly    -- `VVI` 保证每个 id 只和一个 bufnr 对应. id 一旦设置应该无法改变.
--- - cmd? string|string[]     -- `:help jobstart()` cmd
--- - cwd? string             -- `:help jobstart-options` cwd
--- - env? string             -- `:help jobstart-options` env
--- - auto_scroll? boolean    -- goto bottom of the terminal. 在 on_stdout & on_stderr 中触发.
--- - console_output? boolean -- true: 在 console 中执行; false: 在 terminal 中执行.
---
--- - before_run? fun(term: table) -- term:run() 时触发. before jobstart().
--- - after_run?  fun(term: table) -- term:run() 时触发. 在 jobstart() 之后马上执行不用等到 jobdone.
--- - on_open?    fun(term: table) -- BufWinEnter. 同一个 buffer (被多个 win 显示时)每次都会触发.
--- - on_close?   fun(term: table) -- BufWinLeave. 只会在 buffer 离开最后一个 win 的时候触发.
---
--- - on_stdout?  fun(term: table, job_id: integer, data: string[], event: 'stdout')   -- cmd 执行后返回的 data.
--- - on_stderr?  fun(term: table, job_id: integer, data: string[], event: 'stderr')   -- cmd 执行后返回的 err.
--- - on_exit?    fun(term: table, job_id: integer, exit_code: integer, event: 'exit') -- jobdone 之后执行.
---
---@class MyTermOpts
---@field id integer @readonly  VVI: 保证每个 id 只和一个 bufnr 对应. id 一旦设置应该无法改变.
---
---@field cmd string|string[]     `:help jobstart()` cmd
---@field cwd? string             `:help jobstart-options` cwd
---@field env? string             `:help jobstart-options` env
---@field auto_scroll? boolean    goto bottom of the terminal. 在 on_stdout & on_stderr 中触发.
---@field console_output? boolean true: 在 console 中执行; false: 在 terminal 中执行.
---
---以下是 callback functions
---@field before_run? fun(term: MyTerm) term:run() 时触发. before jobstart().
---@field after_run? fun(term: MyTerm)  term:run() 时触发. 在 jobstart() 之后马上执行, 和 on_exit 的区别是不用等到 jobdone.
---@field on_open? fun(term: MyTerm)    BufWinEnter. NOTE: 每次 term:// buffer 被 win 显示的时候都会触发, 同一个 buffer 被多个窗口显示时也会触发.
---@field on_close? fun(term: MyTerm)   BufWinLeave. NOTE: BufWinLeave 只会在 buffer 离开最后一个 win 的时候触发.
---
---@field on_stdout? fun(term: MyTerm, job_id: integer, data: string[], event: 'stdout')
---@field on_stderr? fun(term: MyTerm, job_id: integer, data: string[], event: 'stderr')
---@field on_exit? fun(term: MyTerm, job_id: integer, exit_code: integer, event: 'exit')
