"$schema" = 'https://starship.rs/config-schema.json'

# 禁止在提示符后换行
add_newline = false

# 使用自定义 colors
palette = 'my_colors'

format = """
$username\
${custom.git_branch_main}\
${custom.git_branch_other}\
$hostname\
$git_branch\
$git_status\
$directory\
$fill\
$status\
$cmd_duration\
$line_break\
$character\
"""

[fill]
symbol = " " # 使用空格填充，将后面的内容推向右侧

[username]
# 设置为 true 会让用户名始终显示
show_always = true
style_user = "fg:orange bg:grey_bg"
style_root = "fg:black bg:red_bg bold"  # root 用户时的特殊颜色
format = "[ $user ]($style)"  # 动态加载 user, root style

[hostname]
ssh_only = true  # 只在远程时显示 hostname
ssh_symbol = "🌐"
style = "fg:black bg:magenta_bg bold"
format = "[ $ssh_symbol $hostname ]($style)"

[git_branch]
# symbol = ""
disabled = true

[git_status]
disabled = true

[directory]
style = "fg:white bg:blue_bg bold"
format = "[ $path ]($style)"
truncation_length = 99
truncate_to_repo = false
truncation_symbol = "…/"

[status]
disabled = false
symbol = "err:"     # 区分普通错误和信号(Signal)
success_symbol = ""  # error_code=0 时不显示
style = "fg:red bold"
format = "[ $symbol $int ]($style)"

# 执行时间显示 (如果命令运行超过 2 秒则显示)
[cmd_duration]
min_time = 2_000
style = "fg:grey"
format = "[\\($duration\\)]($style)"

# 替换默认的字符图标
[character]
success_symbol = "[\\$](fg:white)"
error_symbol = "[\\$](fg:white)"

[custom.git_branch_main]
command = "git rev-parse --abbrev-ref HEAD"
when = 'git rev-parse --is-inside-work-tree 2>/dev/null && git rev-parse --abbrev-ref HEAD | grep -qE "^(main|master)$"'
format = "[ 󰌾 $output ]($style)"
style = "fg:black bg:orange_bg bold"

[custom.git_branch_other]
command = "git rev-parse --abbrev-ref HEAD"
when = 'git rev-parse --is-inside-work-tree 2>/dev/null && git rev-parse --abbrev-ref HEAD | grep -qvE "^(main|master)$"'
format = "[  $output ]($style)"
style = "fg:black bg:green_bg bold"


[palettes.my_colors]
white = "251"
black = "236"
red_bg = "196"
magenta_bg = "5"
green_bg = "35"
blue_bg = "25"
orange    = "215"
orange_bg = "208"
grey    = "240"
grey_bg = "237"



