"$schema" = 'https://starship.rs/config-schema.json'

# 禁止在提示符后换行
add_newline = false

# 使用自定义 colors
palette = 'my_colors'

format = """
$username\
${custom.git_branch}\
$hostname\
$git_branch\
$git_status\
$directory\
$fill\
$status\
$cmd_duration\
$line_break\
$character\
"""

[fill]
symbol = " " # 使用空格填充，将后面的内容推向右侧

[username]
# 设置为 true 会让用户名始终显示
show_always = true
style_user = "fg:orange bg:grey_bg"
style_root = "fg:255 bg:red_bg bold"
format = "[ $user ]($style)"

[hostname]
# 只在远程时显示 hostname
ssh_only = true
ssh_symbol = "🌐"
style = "fg:black bg:magenta_bg bold"
format = "[ $ssh_symbol $hostname ]($style)"

[git_branch]
# symbol = ""
disabled = true

[git_status]
disabled = true

[custom.git_branch]
# bg: \e[48;5;xxxm
# fg: \e[38;5;xxxm
# bold: \e[1;xx;xx;xxxm
command = """
branch=$(git rev-parse --abbrev-ref HEAD 2>/dev/null)
dirty=$(git status --porcelain 2>/dev/null | grep -q . && echo 1)
if [[ "$branch" =~ ^(main|master)$ ]]; then
	if [ "$dirty" = "1" ]; then
		printf "\e[48;5;196m\e[1;38;5;255m %s \e[0m" "󰌾 $branch "
	else
		printf "\e[48;5;208m\e[1;38;5;232m %s \e[0m" "󰌾 $branch"
	fi
else
	if [ "$dirty" = "1" ]; then
		printf "\e[48;5;228m\e[1;38;5;235m %s \e[0m" " $branch "
	else
		printf "\e[48;5;35m\e[1;38;5;235m %s \e[0m" " $branch"
	fi
fi
"""
# 当前文件在 git 内的情况下才会触发后续任务
when = 'git rev-parse --is-inside-work-tree 2>/dev/null'
# 不需要 (style), 由 printf 控制颜色
format = "$output"

[directory]
style = "fg:white bg:blue_bg bold"
format = "[ $path ]($style)"
truncation_length = 99
truncate_to_repo = false
truncation_symbol = "…/"

[status]
disabled = false
symbol = "err:"
success_symbol = ""
style = "fg:red bold"
format = "[ $symbol $int ]($style)"

# 执行时间显示 (如果命令运行超过 2 秒则显示)
[cmd_duration]
min_time = 2_000
style = "fg:grey"
format = "[\\($duration\\)]($style)"

# 替换默认的字符图标
[character]
success_symbol = "[\\$](fg:white)"
error_symbol = "[\\$](fg:white)"

# colors
[palettes.my_colors]
white = "252"
black = "235"
red_bg = "196"
magenta_bg = "213"
green_bg = "35"
blue_bg = "25"
orange    = "215"
orange_bg = "208"
grey    = "240"
grey_bg = "237"



