# https://github.com/sxyazi/yazi/blob/main/yazi-config/preset/yazi-default.toml

[mgr]
ratio = [1, 3, 3]

[preview]
wrap = "no"
tab_size = 4

[input]
cursor_blink = true

[plugin]
# prepend_previewers: 这个指令会将你的规则插入到 Yazi 默认规则的 最前面
prepend_previewers = [
	# --- 根据文件名后缀 ---
    { url = "*/", name = "*.pages",     run = "noop" },
    { url = "*/", name = "*.numbers",   run = "noop" },
    { url = "*/", name = "*.key",       run = "noop" },

	# --- 根据文件类型 ---
    { mime = "application/zip", run = 'noop' },
    { mime = "application/pdf", run = 'noop' },
    { mime = "audio/*",         run = 'noop' },
    { mime = "video/*",         run = 'noop' },
]